name: Create Pull Request

on:
  push:
    branches-ignore:
      - "main"

jobs:
  create_pr_repo_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get commit message
        id: commit
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.event.after }})
          echo "::set-output name=message::$COMMIT_MESSAGE"
        shell: bash
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: ${{ steps.commit.outputs.message }}
          pr_reviewer: "volantebjb"